ColorWars/Models/General/Message.cs
using System;

namespace ColorWars.Models
{
    public class Message
    {
        public Guid Id { get; set; }
        public string Sender { get; set; }
        public string Recipient { get; set; }
        public string Content { get; set; }
        public string Color { get; set; }
        public string DisplayPicUrl { get; set; }
        public bool IsRead { get; set; }
        public bool IsRecentlyActive => (DateTime.UtcNow - LastActive).TotalMinutes <= 30;
        public DateTime CreatedDate { get; set; }
        public DateTime LastActive { get; set; }
    }
}

ColorWars/Models/MessagesViewModel.cs
using System.Collections.Generic;

namespace ColorWars.Models
{
    public class MessagesViewModel : BaseViewModel
    {
        public User Correspondent { get; set; }
        public List<Message> AllMessages { get; set; }
        public List<Message> Conversation { get; set; }
        public bool IsBlocked { get; set; }
        public bool CanSendMessage { get; set; }
        public bool ShowReadReceipts { get; set; }
        public bool IsMessageBox { get; set; }
        public string SearchQuery { get; set; }
    }
}

ColorWars/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Mvc;
using ColorWars.Models;
using ColorWars.Repositories;
using System;
using System.Text.RegularExpressions;
using System.Collections.Generic;
using ColorWars.Classes;
using System.Linq;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;

namespace ColorWars.Controllers
{
    public class MessagesController : Controller
    {
        private ILoginRepository _loginRepository;
        private IMessagesRepository _messagesRepository;
        private IUserRepository _userRepository;
        private IPromoCodesRepository _promoCodesRepository;
        private IBlockedRepository _blockedRepository;
        private IItemsRepository _itemsRepository;
        private IChecklistRepository _checklistRepository;
        private IClubRepository _clubRepository;
        private IPointsRepository _pointsRepository;
        private ISettingsRepository _settingsRepository;
        private IAccomplishmentsRepository _accomplishmentsRepository;

        public MessagesController(ILoginRepository loginRepository, IMessagesRepository messagesRepository, IUserRepository userRepository,
        IBlockedRepository blockedRepository, IItemsRepository itemsRepository, IChecklistRepository checklistRepository, IClubRepository clubRepository,
        IPointsRepository pointsRepository, ISettingsRepository settingsRepository, IAccomplishmentsRepository accomplishmentsRepository, IPromoCodesRepository promoCodesRepository)
        {
            _loginRepository = loginRepository;
            _userRepository = userRepository;
            _messagesRepository = messagesRepository;
            _promoCodesRepository = promoCodesRepository;
            _blockedRepository = blockedRepository;
            _itemsRepository = itemsRepository;
            _checklistRepository = checklistRepository;
            _clubRepository = clubRepository;
            _pointsRepository = pointsRepository;
            _settingsRepository = settingsRepository;
            _accomplishmentsRepository = accomplishmentsRepository;
        }

        public IActionResult Index(string username)
        {
            User user = _loginRepository.AuthenticateUser();
            if (user == null)
            {
                return RedirectToAction("Index", "Login", new { ru = $"Messages{(string.IsNullOrEmpty(username) ? "" : $"?username={username}")}" });
            }

            Settings settings = _settingsRepository.GetSettings(user);
            if (settings.CurrentIntroStage != IntroStage.Completed)
            {
                return RedirectToAction("Index", "Intro");
            }

            MessagesViewModel messagesViewModel = GenerateModel(user, username, false);
            messagesViewModel.UpdateViewData(ViewData);
            return View(messagesViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Message(string recipient, string message)
        {
            User user = _loginRepository.AuthenticateUser();
            if (user == null)
            {
                return Json(new Status { Success = false, ErrorMessage = "You are not logged in." });
            }

            if (Helper.IsThrottled(user))
            {
                return Json(new Status { Success = false, ErrorMessage = Resources.ThrottledMessage });
            }

            if (string.IsNullOrEmpty(message))
            {
                return Json(new Status { Success = false, ErrorMessage = "Your message can't be empty." });
            }

            if (message.Length > 1000)
            {
                return Json(new Status { Success = false, ErrorMessage = "Your message is too long." });
            }

            User correspondent = _userRepository.GetUser(recipient);
            if (correspondent == null)
            {
                return Json(new Status { Success = false, ErrorMessage = "This user no longer seems to exist." });
            }

            if (_blockedRepository.HasBlockedUser(correspondent, user, false))
            {
                return Json(new Status { Success = false, ErrorMessage = "You cannot message this user." });
            }

            List<Accomplishment> accomplishments = _accomplishmentsRepository.GetAccomplishments(user);

            if (Helper.IsCourier(correspondent))
            {
                if (message.Contains($"Open Sesame", StringComparison.InvariantCultureIgnoreCase))
                {
                    if (!accomplishments.Exists(x => x.Id == AccomplishmentId.HiddenTreasure))
                    {
                        if (user.GetAgeInHours() >= 1 && DateTime.UtcNow.Hour == user.CreatedDate.Hour)
                        {
                            if (_pointsRepository.AddPoints(user, 10000))
                            {
                                _accomplishmentsRepository.AddAccomplishment(user, AccomplishmentId.HiddenTreasure);
                                return Json(new Status { Success = true, SuccessMessage = $"You successfully wrote the secret message and earned {Helper.GetFormattedPoints(10000)}!", Points = user.GetFormattedPoints() });
                            }
                        }
                        return Json(new Status { Success = false, ErrorMessage = "You cannot enter that secret message at this time. If only you knew when your account was created.", Points = user.GetFormattedPoints() });
                    }
                }
                return Json(new Status { Success = false, ErrorMessage = $"{correspondent.Username} cannot receive any messages. If you have any questions, please post them at the Attention Hall.", ButtonText = "Head to the Attention Hall!", ButtonUrl = "/AttentionHall" });
            }

            if (user.Role < UserRole.Helper)
            {
                Settings settings = _settingsRepository.GetSettings(correspondent, false);
                if (settings.DisableMessages)
                {
                    List<Message> messages = _messagesRepository.GetMessagesBetweenUsernames(user, correspondent, false);
                    if (!messages.Exists(x => x.Sender == correspondent.Username))
                    {
                        return Json(new Status { Success = false, ErrorMessage = $"{correspondent.Username} has disabled messaging." });
                    }
                }
            }

            string strippedMessage = Regex.Replace(message, @"(\r?\n\s*){2,}", Environment.NewLine + Environment.NewLine);
            _messagesRepository.AddMessage(user, correspondent, strippedMessage);

            if (!accomplishments.Exists(x => x.Id == AccomplishmentId.FirstMessage))
            {
                _accomplishmentsRepository.AddAccomplishment(user, AccomplishmentId.FirstMessage);
            }

            return Json(new Status { Success = true });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult GoToConversation(string username)
        {
            User user = _loginRepository.AuthenticateUser();
            if (user == null)
            {
                return Json(new Status { Success = false, ErrorMessage = "You are not logged in." });
            }

            if (Helper.IsThrottled(user))
            {
                return Json(new Status { Success = false, ErrorMessage = Resources.ThrottledMessage });
            }

            if (string.IsNullOrEmpty(username))
            {
                return Json(new Status { Success = false, ErrorMessage = "You must provide a username to message." });
            }

            if (username.Equals(user.Username, StringComparison.InvariantCultureIgnoreCase))
            {
                return Json(new Status { Success = false, ErrorMessage = "You cannot start a conversation with yourself." });
            }

            User correspondent = _userRepository.GetUser(username);
            if (correspondent == null)
            {
                return Json(new Status { Success = false, ErrorMessage = "This user doesn't exist." });
            }

            if (_blockedRepository.HasBlockedUser(correspondent, user, false))
            {
                return Json(new Status { Success = false, ErrorMessage = "You cannot message this user." });
            }

            if (user.Role < UserRole.Helper)
            {
                Settings settings = _settingsRepository.GetSettings(correspondent, false);
                if (settings.DisableMessages)
                {
                    List<Message> messages = _messagesRepository.GetMessagesBetweenUsernames(user, correspondent, false);
                    if (!messages.Exists(x => x.Sender == correspondent.Username))
                    {
                        return Json(new Status { Success = false, ErrorMessage = $"{correspondent.Username} has disabled messaging." });
                    }
                }
            }

            return Json(new Status { Success = true, ReturnUrl = $"Messages?username={correspondent.Username}" });
        }

        [HttpPost]
        public IActionResult Remove(string username)
        {
            User user = _loginRepository.AuthenticateUser();
            if (user == null)
            {
                return Json(new Status { Success = false, ErrorMessage = "You are not logged in." });
            }

            if (Helper.IsThrottled(user))
            {
                return Json(new Status { Success = false, ErrorMessage = Resources.ThrottledMessage });
            }

            User correspondent = _userRepository.GetUser(username);
            if (correspondent == null)
            {
                return Json(new Status { Success = false, ErrorMessage = "This user no longer seems to exist." });
            }


ColorWars/Views/Messages/Index.cshtml
@model MessagesViewModel
<div id="messagesPartialView">
    @if (Model.Correspondent == null)
    {
        @await Html.PartialAsync("_MessagesAllMessagesPartial", Model)
    }
    else
    {
        @await Html.PartialAsync("_MessagesConversationPartial", Model)
    }
</div>

ColorWars/Views/Messages/_MessagesAllMessagesPartial.cshtml
@model MessagesViewModel

<h5 class="inline">
    @if (Model.AllMessages.Count == 50)
    {
        <span>Showing you top <b>@Helper.FormatNumber(Model.AllMessages.Count)</b> conversations</span>
    }
    else
    {
        <span>You have <b>@Helper.FormatNumber(Model.AllMessages.Count)</b> conversation@(Model.AllMessages.Count == 1 ? "" : "s")</span>
    }
</h5>
<div class="pull-right behind-margin-top hidden-xxs">
    <a onclick="$('#modal-new-message').modal();" class="btn btn-sm btn-success no-load-btn">New Message</a>
</div>
<div class="small-padding-top"></div>
<form>
    <div class="padding-top">
        <div class="input-group">
            <input type="text" id="searchQuery" name="searchQuery" class="form-control" placeholder="Search by username" autocomplete="off" onkeyup="delayedKeyUpUpdateMessages(event, this.form);" onkeydown="return event.key != 'Enter';" value="@Model.SearchQuery">
            <span class="input-group-btn">
                <button class="btn btn-secondary btn-rounded" onclick="$('#searchQuery').val('');"><span class="glyphicon glyphicon-remove"></span></button>
            </span>
        </div>
    </div>
</form>
<div class="small-padding-top"></div>
@foreach (Message message in Model.AllMessages)
{
    string correspondent = (message.Sender == Model.User.Username ? message.Recipient : message.Sender);
    <div class="padding-top"></div>
    <div id="@correspondent" class="gray-container white-background @(string.IsNullOrEmpty(Model.SearchQuery) ? "animated fadeIn" : "") clickable message @(message.Recipient == Model.User.Username && !message.IsRead ? "unread-message unread-message-hover" : "hover-container gray-border")" onclick="window.location.href='/Messages?username=@correspondent'">
        <div class="pull-left">
            @if (string.IsNullOrEmpty(message.DisplayPicUrl))
            {
                <div class="circle" id="colored-by-username-@message.Id" data-user-color="@message.Color" value="@correspondent">
                    @correspondent.Substring(0, 1).ToUpper()
                </div>
            }
            else
            {
                <img class="img-circle display-image" src="@message.DisplayPicUrl" />
            }
        </div>
        <div class="image-padding-left small-margin-left ">
            <div>
                <span class="semi-bold">
                    @correspondent
                    @if (message.IsRecentlyActive || correspondent == Helper.GetCourierUsername())
                    {
                        <span class="status-dot win-green-background" data-toggle="tooltip" data-placement="top" title="Last Active: @(correspondent == Helper.GetCourierUsername() ? DateTime.UtcNow.GetTimeSince() : message.LastActive.GetTimeSince())"></span>
                    }
                    <span class="label label-danger hidden-xxs extra-small-margin-left">@(message.Recipient == Model.User.Username && !message.IsRead ? "New" : "")</span>
                </span>
                <span class="pull-right margin-left hidden-xs">
                    <a href="#" onclick="window.event.stopPropagation(); removeAllMessages('@correspondent')"><span style="font-size: 16px;" class="glyphicon glyphicon-remove lose-red" data-toggle="tooltip" data-placement="top" title="Remove"></span></a>
                </span>
                <small class="text-muted pull-right semi-bold">
                    @message.CreatedDate.GetTimeSince()
                </small>
            </div>
            <div class="text-muted small-padding-top">
                <div class="truncate">
                    @if (message.Sender == Model.User.Username)
                    {
                        <span class="fas fa-share"></span>
                    }
                    @Html.Raw(Helper.MakeLinkClickable(message.Content))
                </div>
            </div>
        </div>
    </div>
}
@if (Model.AllMessages.Count == 0)
{
    <h2 class="text-center primary-color small-padding-bottom"><span class="fas fa-envelope-open"></span></h2>
    <div class="alert alert-info">
        @if (string.IsNullOrEmpty(Model.SearchQuery))
        {
            <span>You have <b>no conversations</b>. Check out someone's profile and send them a message!</span>
        }
        else
        {
            <span>No conversations matched your search of <b>@Model.SearchQuery</b>.</span>
        }
    </div>
}
<div class="modal fade" id="modal-new-message" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">New Message</h4>
            </div>
            <div class="modal-body">
                <div class="text-muted padding-bottom">
                    Enter a username to send them a message.
                </div>
                <form action="@Url.Action("GoToConversation", "Messages")" method="POST" onsubmit="submitNewMessagesForm(event, this);">
                    @Html.AntiForgeryToken()
                    <div class="input-group">
                        <input type="text" class="form-control" name="username" placeholder="Username" autofocus maxlength="15" required />
                        <span class="input-group-btn"><button type="submit" class="btn btn-primary btn-rounded">Message</button></span>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

ColorWars/Views/Messages/_MessagesBoxAllPartial.cshtml
@model MessagesViewModel

<div class="text-center small-padding-bottom"><a onclick="toggleMessagesBox();" class="btn btn-block btn-primary">Close</a></div>
@foreach (Message message in Model.AllMessages)
{
    string correspondent = (message.Sender == Model.User.Username ? message.Recipient : message.Sender);
    <div class="gray-container white-background large-padding @(string.IsNullOrEmpty(Model.SearchQuery) ? "animated fadeIn" : "") clickable message @(message.Recipient == Model.User.Username && !message.IsRead ? "unread-message unread-message-hover" : "hover-container gray-border")" onclick="updateMessagesBox('@correspondent', true);">
        <div class="pull-left small-margin-right">
            @if (string.IsNullOrEmpty(message.DisplayPicUrl))
            {
                <div class="circle extra-small-circle" id="colored-by-username-@message.Id" data-user-color="@message.Color" value="@correspondent">
                    @correspondent.Substring(0, 1).ToUpper()
                </div>
            }
            else
            {
                <img class="img-circle display-image display-image-small" src="@message.DisplayPicUrl" />
            }
        </div>
        <div class="small-padding-top">
            <div>
                <span class="semi-bold">
                    @correspondent
                </span>
                @if (!message.IsRead && message.Sender != Model.User.Username)
                {
                    <span class="text-muted pull-right label label-danger">
                        New
                    </span>
                }
                else if (message.IsRecentlyActive || correspondent == Helper.GetCourierUsername())
                {
                    <span class="status-dot win-green-background" data-toggle="tooltip" data-placement="top" title="Last Active: @(correspondent == Helper.GetCourierUsername() ? DateTime.UtcNow.GetTimeSince() : message.LastActive.GetTimeSince())"></span>
                }
            </div>
            <div class="text-muted small-padding-top">
                <div class="truncate">
                    @if (message.Sender == Model.User.Username)
                    {
                        <span class="fas fa-share"></span>
                    }
                    @Html.Raw(Helper.MakeLinkClickable(message.Content))
                </div>
            </div>
        </div>
    </div>
    <div class="small-padding-top"></div>
}
@if (Model.AllMessages.Count == 0)
{
    <h2 class="text-center primary-color small-padding-bottom"><span class="fas fa-envelope-open"></span></h2>
    <div class="alert alert-info">
        You have <b>no conversations</b>. Check out someone's profile and send them a message!
    </div>
}

ColorWars/Views/Messages/_MessagesBoxConversationPartial.cshtml
@model MessagesViewModel

<input type="hidden" id="messageCorrespondent" value="@Model.Correspondent.Username" />
<h5 class="small-margin-bottom">Convo with <a href="/Messages?username=@Model.Correspondent.Username">@Model.Correspondent.Username</a></h5>
<b><a class="clickable" onclick="updateMessagesBox('', true);"><span class="glyphicon glyphicon-chevron-left"></span> All Messages @(Model.AllMessages.Count(x => x.Recipient == Model.User.Username && !x.IsRead) > 0 ? $"({Helper.FormatNumberShortened(Model.AllMessages.Count(x => x.Recipient == Model.User.Username && !x.IsRead))})" : "")</a></b>
<div class="small-padding-top"></div>
<div id="scrollContainer" class="message-container small-message-container">
    @await Html.PartialAsync("_MessagesConversationBodyPartial", Model)
</div>
<form action="@Url.Action("Message", "Messages")" method="POST" onsubmit="submitMessagesForm(event, this, '@Model.Correspondent.Username', true);" class="small-padding-top">
    <div id="message-container">
        <input type="hidden" name="recipient" value="@Model.Correspondent.Username" />
        @Html.AntiForgeryToken()
        <div class="input-group">
            <input type="text" class="form-control" id="message" name="message" placeholder="Your message" autocomplete="off" autofocus maxlength="1000" required>
            <span class="input-group-btn "><button type="submit" class="btn btn-primary btn-rounded @(Model.CanSendMessage ? "" : "disabled")">Send</button></span>
        </div>
    </div>
</form>

ColorWars/Views/Messages/_MessagesConversationBodyPartial.cshtml
@model MessagesViewModel
<div id="conversationContainer">
    @if (Model.Conversation.Count == 0)
    {
        <div class="large-padding-top"></div>
        <div class="alert alert-info no-margin-top no-margin-bottom">
            You have no messages with <b>@Model.Correspondent.Username</b>. Send one below to start a conversation!
        </div>
    }
    @{
        int i = 0;
        Guid lastMessageId = Model.Conversation.FindAll(x => x.Sender == Model.User.Username).LastOrDefault()?.Id ?? Guid.Empty;
    }
    @foreach (Message message in Model.Conversation)
    {
        <div class="large-padding-top"></div>
        @if (i == 0 || (int)(Model.Conversation[i].CreatedDate - Model.Conversation[i - 1].CreatedDate).TotalMinutes >= 15)
        {
            <div class="large-padding-bottom text-center text-muted semi-bold">
                @message.CreatedDate.GetTimeSince()
            </div>
        }
        i++;
        <div id="@(Model.IsMessageBox && i == Model.Conversation.Count ? "last-message" : "")" class="row">
            @if (message.Recipient == Model.User.Username)
            {
                <div class="col-xs-9 link-without-format">
                    <div id="@message.Id" class="message-bubble @((DateTime.UtcNow - message.CreatedDate).TotalSeconds < 2 ? "animated fadeInLeft" : "")" data-toggle="tooltip" data-placement="right" title="@(Model.IsMessageBox ? "" : message.CreatedDate.GetTimeSince())">
                        @Html.Raw(Helper.MakeUserMessageItalicized(message.Sender, Helper.MakeUserMessageClickable(message.Sender, Helper.MakeLinkClickable(message.Content))))
                    </div>
                </div>
                <div class="col-xs-3">
                </div>
            }
            @if (message.Sender == Model.User.Username)
            {
                <div class="col-xs-3">
                </div>
                <div class="col-xs-9 text-right">
                    <div id="@message.Id" class="message-bubble text-left gray-background-color @((DateTime.UtcNow - message.CreatedDate).TotalSeconds < 2 ? "animated fadeInRight" : "")" data-toggle="tooltip" data-placement="left" title="@(Model.IsMessageBox ? "" : message.CreatedDate.GetTimeSince())" style="color: black;">
                        @Html.Raw(Helper.MakeUserMessageItalicized(message.Sender, Helper.MakeUserMessageClickable(message.Sender, Helper.MakeLinkClickable(message.Content))))
                    </div>
                </div>
            }
        </div>
        @if (message.Id == lastMessageId)
        {
            <div class="@((DateTime.UtcNow - message.CreatedDate).TotalSeconds < 2 ? "animated fadeInRight" : "")" data-toggle="tooltip" data-placement="right" title="@(Model.IsMessageBox ? "" : message.IsRead && Model.ShowReadReceipts ? "Seen" : "Delivered")">
                <span class="fas fa-check@(message.IsRead && (Model.User.Role > UserRole.Default || Model.ShowReadReceipts)  ? "-double" : "") pull-right win-green"></span>
            </div>
        }
    }
    <div class="large-padding-top"></div>
</div>

ColorWars/Views/Messages/_MessagesConversationPartial.cshtml
@model MessagesViewModel

<input type="hidden" id="messageCorrespondent" value="@Model.Correspondent.Username" />
<h5>Conversation with <a href="/User/@Model.Correspondent.Username">@(Model.Correspondent.Username == Model.Correspondent.GetFriendlyName() ? $"{Model.Correspondent.Username}" : $"{Model.Correspondent.GetFriendlyName()} ({Model.Correspondent.Username})")</a>  <a href="/Preferences#blockUsers" class="label label-danger" data-toggle="tooltip" data-placement="top" title="You've blocked @Model.Correspondent.Username so they can't reply to your messages.">@(Model.IsBlocked ? "Blocked" : "")</a></h5>
<b><a href="/Messages"><span class="glyphicon glyphicon-chevron-left"></span> All Messages @(Model.AllMessages.Count(x => x.Recipient == Model.User.Username && !x.IsRead) > 0 ? $"({Helper.FormatNumberShortened(Model.AllMessages.Count(x => x.Recipient == Model.User.Username && !x.IsRead))})" : "")</a></b>
@if (Model.Conversation.Count > 0)
{
    <b class="pull-right">
        <a class="lose-red clickable" onclick="removeAllMessages('@Model.Correspondent.Username')" data-toggle="tooltip" data-placement="top" title="Remove"><span class="glyphicon glyphicon-remove"></span><span class="hidden-xs"> Remove</span></a>
        @if (!Model.IsBlocked)
        {
            <a href="/Preferences?blockUser=@Model.Correspondent.Username#blockUsers" class="text-warning" style="margin-left: 5px;" data-toggle="tooltip" data-placement="top" title="Block"><span class="glyphicon glyphicon-minus-sign"></span><span class="hidden-xs"> Block</span></a>
        }
    </b>
}
<div class="padding-top"></div>
<div id="scrollContainer" class="message-container">
    @await Html.PartialAsync("_MessagesConversationBodyPartial", Model)
</div>
<form action="@Url.Action("Message", "Messages")" method="POST" onsubmit="submitMessagesForm(event, this, '@Model.Correspondent.Username');" class="padding-top">
    <div id="message-container" class="form-group gray-container">
        <input type="hidden" name="recipient" value="@Model.Correspondent.Username" />
        @Html.AntiForgeryToken()
        <div class="input-group">
            <input type="text" class="form-control" id="message" name="message" placeholder="Your message..." autocomplete="off" autofocus maxlength="1000" required>
            <span class="input-group-btn "><button type="submit" class="btn btn-primary btn-rounded @(Model.CanSendMessage ? "" : "disabled")">Send</button></span>
        </div>
    </div>
</form>