ColorWars/Models/AttentionHallViewModel.cs
using System.Collections.Generic;

namespace ColorWars.Models
{
    public class AttentionHallViewModel : BaseViewModel
    {
        public List<AttentionHallPost> AttentionHallPosts { get; set; }
        public AttentionHallPost AttentionHallPost { get; set; }
        public List<AttentionHallComment> AttentionHallComments { get; set; }
        public List<Item> UserItems { get; set; }
        public List<Accomplishment> UserAccomplishments { get; set; }
        public List<MatchTag> UserMatchTags { get; set; }
        public JobState? JobState { get; set; }
        public int TotalPages { get; set; }
        public int CurrentPage { get; set; }
        public AttentionHallPostsFilter CurrentFilter { get; set; }
        public AttentionHallPostType TypeFilter { get; set; }
    }
}

ColorWars/Controllers/AttentionHallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using ColorWars.Classes;
using ColorWars.Models;
using ColorWars.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ColorWars.Controllers
{
    public class AttentionHallController : Controller
    {
        private ILoginRepository _loginRepository;
        private IAttentionHallRepository _attentionHallRepository;
        private IItemsRepository _itemsRepository;
        private ISettingsRepository _settingsRepository;
        private IUserRepository _userRepository;
        private IBlockedRepository _blockedRepository;
        private IAccomplishmentsRepository _accomplishmentsRepository;
        private IJobsRepository _jobsRepository;
        private IMatchHistoryRepository _matchHistoryRepository;
        private INotificationsRepository _notificationsRepository;
        private IAdminHistoryRepository _adminHistoryRepository;

        public AttentionHallController(ILoginRepository loginRepository, IAttentionHallRepository attentionHallRepository, IItemsRepository itemsRepository,
        ISettingsRepository settingsRepository, IUserRepository userRepository, IAccomplishmentsRepository accomplishmentsRepository,
        IJobsRepository jobsRepository, IMatchHistoryRepository matchHistoryRepository, IBlockedRepository blockedRepository, INotificationsRepository notificationsRepository,
        IAdminHistoryRepository adminHistoryRepository)
        {
            _loginRepository = loginRepository;
            _itemsRepository = itemsRepository;
            _attentionHallRepository = attentionHallRepository;
            _settingsRepository = settingsRepository;
            _userRepository = userRepository;
            _blockedRepository = blockedRepository;
            _accomplishmentsRepository = accomplishmentsRepository;
            _jobsRepository = jobsRepository;
            _matchHistoryRepository = matchHistoryRepository;
            _notificationsRepository = notificationsRepository;
            _adminHistoryRepository = adminHistoryRepository;
        }

        public IActionResult Index(int id, int page, AttentionHallPostsFilter? filter, AttentionHallPostType? type)
        {
            User user = _loginRepository.AuthenticateUser();
            if (user == null)
            {
                return RedirectToAction("Index", "Login", new { ru = $"AttentionHall?id={id}&page={page}&filter={(filter.HasValue ? filter : AttentionHallPostsFilter.Popular)}&type={(type.HasValue ? type : AttentionHallPostType.None)}" });
            }

            Settings settings = _settingsRepository.GetSettings(user);
            if (filter.HasValue)
            {
                if (settings.AttentionHallPostsFilter != filter)
                {
                    settings.AttentionHallPostsFilter = filter.Value;
                    _settingsRepository.SetSetting(user, nameof(settings.AttentionHallPostsFilter), settings.AttentionHallPostsFilter.ToString());
                }
            }
            else
            {
                filter = settings.AttentionHallPostsFilter;
            }
            if (type.HasValue)
            {
                if (settings.AttentionHallPostsTypeFilter != type)
                {
                    settings.AttentionHallPostsTypeFilter = type.Value;
                    _settingsRepository.SetSetting(user, nameof(settings.AttentionHallPostsTypeFilter), settings.AttentionHallPostsTypeFilter.ToString());
                }
            }
            else
            {
                type = settings.AttentionHallPostsTypeFilter;
            }

            AttentionHallViewModel attentionHallViewModel = GenerateModel(user, id, page, false, filter.Value, type.Value);
            attentionHallViewModel.UpdateViewData(ViewData);
            return View(attentionHallViewModel);
        }

        public IActionResult Create(int id)
        {
            User user = _loginRepository.AuthenticateUser();
            if (user == null)
            {
                return RedirectToAction("Index", "Login", new { ru = $"AttentionHall/Create" });
            }

            AttentionHallViewModel attentionHallViewModel = GenerateModel(user, id, 0, true);
            attentionHallViewModel.UpdateViewData(ViewData);
            return View(attentionHallViewModel);
        }

        [HttpPost]
        public IActionResult Vote(int id, AttentionHallPointType vote)
        {
            User user = _loginRepository.AuthenticateUser();
            if (user == null)
            {
                return Json(new Status { Success = false, ErrorMessage = "You are not logged in." });
            }

            if (Helper.IsThrottled(user))
            {
                return Json(new Status { Success = false, ErrorMessage = Resources.ThrottledMessage });
            }

            AttentionHallPost attentionHallPost = _attentionHallRepository.GetAttentionHallPost(user, id);
            if (attentionHallPost == null)
            {
                return Json(new Status { Success = false, ErrorMessage = "This post does not exist." });
            }

            if (_attentionHallRepository.SetAttentionHallPoint(user, attentionHallPost, vote))
            {
                string domain = Helper.GetDomain();
                Task.Run(() =>
                {
                    if (attentionHallPost.Points == 4 && vote == AttentionHallPointType.Positive && user.Username != attentionHallPost.Username)
                    {
                        User postUser = _userRepository.GetUser(attentionHallPost.Username);
                        if (postUser != null)
                        {
                            _notificationsRepository.AddNotification(postUser, "Your Attention Hall post received 5 votes!", NotificationLocation.AttentionHall, $"/AttentionHall?id={attentionHallPost.Id}", string.Empty, domain);
                        }
                    }
                    if (attentionHallPost.Points == 19 && vote == AttentionHallPointType.Positive)
                    {
                        User postUser = _userRepository.GetUser(attentionHallPost.Username);
                        if (postUser != null)
                        {
                            List<Accomplishment> accomplishments = _accomplishmentsRepository.GetAccomplishments(postUser, false);
                            if (!accomplishments.Exists(x => x.Id == AccomplishmentId.PopularAttentionHallPost))
                            {
                                _accomplishmentsRepository.AddAccomplishment(postUser, AccomplishmentId.PopularAttentionHallPost, false, domain);
                            }
                        }
                    }
                });
            }

            return Json(new Status { Success = true });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(string title, string post, int editId, AttentionHallPostType postType, Guid selectedAccomplishment, Guid selectedItem, string selectedMatchTag, AttentionHallFlair flair)
        {
            User user = _loginRepository.AuthenticateUser();
            if (user == null)
            {
                return Json(new Status { Success = false, ErrorMessage = "You are not logged in." });
            }

            if (Helper.IsThrottled(user))
            {
                return Json(new Status { Success = false, ErrorMessage = Resources.ThrottledMessage });
            }

            if (string.IsNullOrEmpty(title))
            {
                return Json(new Status { Success = false, ErrorMessage = "You need to write a title for your post." });
            }

            if (title.Length > 50)
            {
                return Json(new Status { Success = false, ErrorMessage = "You post title is too long." });
            }

            if (string.IsNullOrEmpty(post))
            {
                return Json(new Status { Success = false, ErrorMessage = "You need to write a post." });
            }

            if (post.Length > 2500)
            {
                return Json(new Status { Success = false, ErrorMessage = $"Your post cannot be more than {Helper.FormatNumber(2500)} characters." });
            }

            AttentionHallPost attentionHallPost = null;
            if (editId > 0)
            {
                attentionHallPost = _attentionHallRepository.GetAttentionHallPost(user, editId);
                if (attentionHallPost != null && attentionHallPost.Username != user.Username)
                {
                    return Json(new Status { Success = false, ErrorMessage = "You cannot edit this Attention Hall post." });
                }
            }

            post = HttpUtility.HtmlEncode(Regex.Replace(post, @"(\r?\n\s*){2,}", Environment.NewLine + Environment.NewLine));

            if (attentionHallPost == null)
            {
                if (postType == AttentionHallPostType.None)
                {
                    return Json(new Status { Success = false, ErrorMessage = "You need to choose what your post is about." });
                }

                Settings settings = _settingsRepository.GetSettings(user);

                int totalMinutesSinceLastPost = (int)(DateTime.UtcNow - settings.LastAttentionHallPostDate).TotalMinutes;
                if (totalMinutesSinceLastPost < 5)
                {
                    return Json(new Status { Success = false, ErrorMessage = $"You've made a post too recently. Try again in {5 - totalMinutesSinceLastPost} minute{(5 - totalMinutesSinceLastPost == 1 ? "" : "s")}." });
                }

                Accomplishment accomplishment = null;
                Item item = null;
                MatchTag matchTag = null;

ColorWars/Views/AttentionHall/Create.cshtml
@model AttentionHallViewModel

<div id="attentionHallCreatePartialView">
    @await Html.PartialAsync("_AttentionHallCreatePartial", Model)
</div>

ColorWars/Views/AttentionHall/Index.cshtml
@model AttentionHallViewModel

<div id="attentionHallPartialView">
    @if (Model.AttentionHallPost == null)
    {
        @await Html.PartialAsync("_AttentionHallAllPartial", Model)
    }
    else
    {
        @await Html.PartialAsync("_AttentionHallPostPartial", Model)
    }
</div>

ColorWars/Views/AttentionHall/_AttentionHallAllPartial.cshtml
@model AttentionHallViewModel

<div class="dropdown inline">
    <button class="btn btn-sm btn-default dropdown-toggle" type="button" data-toggle="dropdown">
        Filter by <b class="hidden-xs">@Model.CurrentFilter.GetDisplayName()</b>
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        <li><a href="/AttentionHall?page=@Model.CurrentPage&filter=@AttentionHallPostsFilter.Popular&type=@Model.TypeFilter">Popular</a></li>
        <li><a href="/AttentionHall?page=@Model.CurrentPage&filter=@AttentionHallPostsFilter.Newest&type=@Model.TypeFilter">Newest</a></li>
        <li><a href="/AttentionHall?page=@Model.CurrentPage&filter=@AttentionHallPostsFilter.AllTime&type=@Model.TypeFilter">All-Time</a></li>
        <li><a href="/AttentionHall?page=@Model.CurrentPage&filter=@AttentionHallPostsFilter.UserCreated&type=@Model.TypeFilter">Your Posts</a></li>
    </ul>
</div>
<div class="dropdown inline">
    <button class="btn btn-sm btn-default dropdown-toggle" type="button" data-toggle="dropdown">
        <span class="hidden-xs">
            <b>@Model.TypeFilter.GetDisplayName()</b>
            <span class="caret"></span>
        </span>
        <span class="visible-xs">
            Type
            <span class="caret"></span>
        </span>
    </button>
    <ul class="dropdown-menu">
        <li><a href="/AttentionHall?page=@Model.CurrentPage&filter=@Model.CurrentFilter&type=@AttentionHallPostType.None">All</a></li>
        <li><a href="/AttentionHall?page=@Model.CurrentPage&filter=@Model.CurrentFilter&type=@AttentionHallPostType.Accomplishment">Accomplishments</a></li>
        <li><a href="/AttentionHall?page=@Model.CurrentPage&filter=@Model.CurrentFilter&type=@AttentionHallPostType.Item">Items</a></li>
        <li><a href="/AttentionHall?page=@Model.CurrentPage&filter=@Model.CurrentFilter&type=@AttentionHallPostType.MatchTag">Match Tags</a></li>
        <li><a href="/AttentionHall?page=@Model.CurrentPage&filter=@Model.CurrentFilter&type=@AttentionHallPostType.General">General</a></li>
    </ul>
</div>
<div class="pull-right">
    <a href="/AttentionHall/Create" class="btn btn-sm btn-success">New Post</a>
</div>
<h5 class="visible-xs small-padding-left">@Model.CurrentFilter.GetDisplayName() - @Model.TypeFilter.GetDisplayName()</h5>
<div class="large-padding-top hidden-xs"></div>
@foreach (AttentionHallPost attentionHallPost in Model.AttentionHallPosts)
{
    <div id="@attentionHallPost.Id" class="feed-container clickable hover-container" onclick="window.location.href='/AttentionHall?id=@attentionHallPost.Id&page=@Model.CurrentPage'">
        <div class="pull-left text-center @(attentionHallPost.Type == AttentionHallPostType.General ? "extra-large-margin-right" : "large-margin-right")">
            <span class="glyphicon glyphicon-triangle-top @(attentionHallPost.UserVote == AttentionHallPointType.Positive ? "win-green" : "text-muted hover-win-green") clickable grow" onclick="attentionHallVote('@attentionHallPost.Id', '@AttentionHallPointType.Positive', '@Model.CurrentPage', false); event.stopPropagation();"></span>
            <h4 class="@(attentionHallPost.Points > 0 ? "win-green" : attentionHallPost.Points < 0 ? "lose-red" : "")">
                @Helper.FormatNumberShortened(attentionHallPost.Points)
            </h4>
            <span class="glyphicon glyphicon-triangle-bottom @(attentionHallPost.UserVote == AttentionHallPointType.Negative ? "lose-red" : "text-muted hover-lose-red") clickable grow" onclick="attentionHallVote('@attentionHallPost.Id', '@AttentionHallPointType.Negative', '@Model.CurrentPage', false); event.stopPropagation();"></span>
        </div>
        @if (attentionHallPost.Type == AttentionHallPostType.Accomplishment)
        {
            <img class="pull-left attention-hall-accomplishment-dimensions extra-small-margin-right hidden-xs" src="@Helper.GetImageUrl(attentionHallPost.Accomplishment.ImageUrl)" />
        }
        else if (attentionHallPost.Type == AttentionHallPostType.Item)
        {
            <img class="pull-left attention-hall-item-dimensions margin-right small-margin-left padding-bottom hidden-xs" src="@Helper.GetImageUrl(attentionHallPost.Item.ImageUrl)" />
        }
        else if (attentionHallPost.Type == AttentionHallPostType.MatchTag)
        {
            <span class="pull-left margin-right small-margin-left padding-bottom circle small-circle attention-hall-match-tag-dimensions hidden-xs" id="colored-by-username-@attentionHallPost.MatchTag.TagUsername" value="@attentionHallPost.MatchTag.TagUsername" data-user-color="@attentionHallPost.MatchTag.Color"><div class="extra-small-padding-top">@attentionHallPost.MatchTag.TagUsername.Substring(0, 1).ToUpper()</div></span>
        }
        <div class="@(attentionHallPost.Type == AttentionHallPostType.General ? "" : "non-mobile-image-extra-large-padding-left")">
            <small>
                Posted by <a href="/User/@attentionHallPost.Username">@attentionHallPost.Username</a>
            </small>
            <small class="text-muted pull-right hidden-xs">@attentionHallPost.CreatedDate.GetTimeSince()</small>
        </div>
        <hr class="vertical-margins"/>
        <div class="small-padding-bottom @(attentionHallPost.Accomplishment == null && attentionHallPost.Item == null ? "" : "non-mobile-image-extra-large-padding-left")">
            <h4 class="grid">@attentionHallPost.Title</h4>
        </div>
        <div class="padding-top"></div>
        <div class="extra-small-padding-top">
            <h6 class="text-muted no-margin-bottom">
                @if (attentionHallPost.Type == AttentionHallPostType.General && attentionHallPost.Flair != AttentionHallFlair.None)
                {
                    <span class="label label-primary">@attentionHallPost.Flair.GetDisplayName()</span>
                }
                else
                {
                    <span>@attentionHallPost.Type.GetDisplayName()</span>
                }
                <span class="pull-right">
                    @Helper.FormatNumberShortened(attentionHallPost.TotalComments) Comment@(attentionHallPost.TotalComments == 1 ? "" : "s")
                </span>
            </h6>
        </div>
    </div>
    <div class="large-padding-top"></div>
}
@if (Model.AttentionHallPosts.Count == 0)
{
    <div class="alert alert-info">
        @if  (Model.CurrentFilter == AttentionHallPostsFilter.UserCreated)
        {
            <span>
                It looks like you haven't made any posts. Why don't you <a class="alert-link" href="/AttentionHall/Create">create one</a>?
            </span>
        }
        else
        {
            <span>
                It looks like there are no posts. Why don't you <a class="alert-link" href="/AttentionHall/Create">create one</a>?
            </span>
        }
    </div>
}
@if (Model.TotalPages > 1)
{
    <div class="text-center">
        <ul class="pagination pagination-sm">
            @for (int i = 0; i < Math.Min(Model.TotalPages, 10); i++)
            {
                <li class="page-item @(Model.CurrentPage == i ? "disabled" : "")">
                    <a class="page-link" href="/AttentionHall?page=@i">@(i + 1)</a>
                </li>
            }
        </ul>
    </div>
}

ColorWars/Views/AttentionHall/_AttentionHallCreatePartial.cshtml
@model AttentionHallViewModel

<div class="gray-container">
    @if (Model.AttentionHallPost == null)
    {
        <span>
            Make a post introducing yourself or write about an accomplishment, item, or general achievement.
        </span>
    }
    else
    {
        <span>
            You can make changes to the title and content of your Attention Hall post.
        </span>
    }
</div>
<form action="@Url.Action("Create", "AttentionHall")" method="POST" onsubmit="submitAttentionHallCreateForm(event, this);" class="padding-top">
    <div class="form-group">
        <label for="title">Post Title</label>
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil" aria-hidden="true"></i></span>
            <input type="text" class="form-control" id="title" name="title" placeholder="Title of your post" maxlength="50" value="@Model.AttentionHallPost?.Title" required>
        </div>
    </div>
    <div class="form-group">
        <label for="post">
            Post
        </label>
        <textarea class="form-control" name="post" rows="3" id="post" placeholder="Write your post..." autocomplete="off" onkeyup="updateAttentionHallPostCountMessage();" required>@Model.AttentionHallPost?.Content</textarea>
        <h6 class="pull-right text-muted" id="attentionHallPostCountMessage">@Helper.FormatNumber((2500 - (Model.AttentionHallPost?.Content?.Length ?? 0))) remaining</h6>
    </div>
    @if (Model.AttentionHallPost == null)
    {
        <div class="form-group">
            <div>
                <label for="postType">Your post is about...</label>
            </div>
            <label class="radio-inline">
                <input type="radio" name="postType" value="@AttentionHallPostType.Accomplishment" required onchange="showAttentionHallPostContainer('@AttentionHallPostType.Accomplishment')">An Accomplishment
            </label>
            <label class="radio-inline">
                <input type="radio" name="postType" value="@AttentionHallPostType.Item" required onchange="showAttentionHallPostContainer('@AttentionHallPostType.Item')">An Item
            </label>
            <label class="radio-inline">
                <input type="radio" name="postType" value="@AttentionHallPostType.MatchTag" required onchange="showAttentionHallPostContainer('@AttentionHallPostType.MatchTag')">A Match Tag
            </label>
            <label class="radio-inline">
                <input type="radio" name="postType" value="@AttentionHallPostType.General" required onchange="showAttentionHallPostContainer('@AttentionHallPostType.General')">General Post
            </label>
            <div id="generalContainer" style="display: none;">
                <div class="form-group padding-top">
                    <label for="flair">Pick a flair for this post:</label>
                    <select class="form-control" id="flair" name="flair">
                        @foreach (AttentionHallFlair attentionHallFlair in Enum.GetValues(typeof(AttentionHallFlair)).Cast<AttentionHallFlair>().OrderByDescending(x => (int)x == 0).ThenBy(x => x.GetDisplayName()).ToList())
                        {
                            <option value="@((int)attentionHallFlair)">@attentionHallFlair.GetDisplayName()</option>
                        }
                    </select>
                </div>
            </div>
            <div id="accomplishmentContainer" style="display: none;">
                <div class="padding-top"></div>
                @if (Model.UserAccomplishments.Count > 0)
                {
                    <div class="alert alert-info no-margin-bottom">
                        Choose an accomplishment that your post is about.
                    </div>
                }
                <h5>Accomplishments (@Helper.FormatNumber(Model.UserAccomplishments.Count))</h5>
                <div class="grid-container grid-container--fit">
                    @foreach (Accomplishment accomplishment in Model.UserAccomplishments)
                    {
                        <div class="grid-container-no-padding grid-element text-center clickable grow" onclick="attentionHallAccomplishmentSelected(this);" id="@accomplishment.SelectionId">
                            <div>
                                <img class="accomplishment-dimensions" src="@Helper.GetImageUrl(accomplishment.ImageUrl)" alt="@accomplishment.Description" title="@accomplishment.Description">
                                <div>
                                    <h5>@accomplishment.Name</h5>
                                    <p><i><small>@accomplishment.Description</small></i></p>
                                </div>
                            </div>
                            <div>
                                <b><small class="no-margin-top no-margin-bottom text-muted">@Math.Round(accomplishment.PercentOwned, 1)% Earned</small></b>
                            </div>
                            <div>
                                <b><small class="text-muted" data-toggle="tooltip" data-placement="top" title="Earned @accomplishment.ReceivedDate.GetTimeSince()">@accomplishment.Category</small></b>
                            </div>
                        </div>
                    }
                </div>
                @if (Model.UserAccomplishments.Count == 0)
                {
                    <div class="alert alert-info">
                        You don't have any accomplishments to make a post about.
                    </div>
                }
            </div>
            <div id="itemContainer" style="display: none;">
                <div class="padding-top"></div>
                @if (Model.UserItems.Count > 0)
                {
                    <div class="alert alert-info no-margin-bottom">
                        Choose an item that your post is about.
                    </div>
                }
                <h5>Items (@Helper.FormatNumber(Model.UserItems.Count))</h5>
                <div class="grid-container grid-container--fit">
                    @foreach (Item item in Model.UserItems)
                    {
                        <div class="grid-container-no-padding grid-element text-center clickable grow" onclick="attentionHallItemSelected(this);" id="@item.SelectionId">
                            <div>
                                <img class="item-dimensions" src="@Helper.GetImageUrl(item.ImageUrl)" alt="@item.Description" title="@item.Description">
                                <div>
                                    <h5>@item.Name</h5>
                                    <p><i><small>@item.Description</small></i></p>
                                </div>
                            </div>
                            <div>
                                @if (item.Tier > RelicId.None)
                                {
                                    <div data-toggle="tooltip" data-placement="top" title="Needs the @item.Tier Relic.">
                                        <img class="relic-tier-dimensions" src="@Helper.GetImageUrl($"Relics/{item.Tier}.png")" />
                                    </div>
                                }
                                <div>
                                    <small class="semi-bold">@(item.Uses > 0 ? $"{item.Uses} Use{(item.Uses != 1 ? "s" : "")} {(item.TotalUses <= item.Uses ? "" : " Left")}" : "")</small>
                                </div>
                                <div>
                                    <span data-toggle="tooltip" data-placement="top" title="@Helper.FormatNumber(item.GetAgeInHours()) hour@(item.GetAgeInHours() == 1 ? "" : "s") old">
                                        <small>
                                            @item.Category <span class="@Helper.GetItemConditionColor(item.Condition)">(@item.Condition)</span>
                                        </small>
                                    </span>
                                </div>
                                <div>
                                    <small class="text-muted">~@Helper.GetFormattedPoints(item.Points)</small>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                @if (Model.UserItems.Count == 0)
                {
                    <div class="alert alert-info">
                        You don't have any items to make a post about.
                    </div>
                }
            </div>
            <div id="matchTagsContainer" style="display: none;">
                <div class="padding-top"></div>
                @if (Model.UserMatchTags.Count > 0)
                {
                    <div class="alert alert-info no-margin-bottom">
                        Choose a Match Tag that your post is about.
                    </div>
                }
                <h5>Match Tags (@Helper.FormatNumber(Model.UserMatchTags.Count))</h5>
                <div class="grid-container grid-container--fit">
                    @foreach (MatchTag matchTag in Model.UserMatchTags)
                    {
                        <div class="grid-container-no-padding grid-element text-center clickable grow" onclick="attentionHallMatchTagSelected(this);" id="@matchTag.TagUsername">
                            <div class="center-circle">
                                <div class="circle" id="colored-by-username-@matchTag.TagUsername" data-user-color="@matchTag.Color" value="@matchTag.TagUsername">
                                    @matchTag.TagUsername.Substring(0, 1).ToUpper()
                                </div>
                            </div>
                            <div>
                                <h5><a href="/User/@matchTag.TagUsername">@matchTag.TagUsername</a></h5>
                                <h5><small>@Helper.FormatNumber(matchTag.Wins) Win@(matchTag.Wins == 1 ? "" : "s")</small></h5>
                            </div>
                        </div>
                    }
                </div>
                @if (Model.UserMatchTags.Count == 0)
                {
                    <div class="alert alert-info">
                        You don't have any Match Tags to make a post about.
                    </div>
                }
            </div>
        </div>
        <input type="hidden" id="selectedAccomplishment" name="selectedAccomplishment" />
        <input type="hidden" id="selectedItem" name="selectedItem" />
        <input type="hidden" id="selectedMatchTag" name="selectedMatchTag" />
    }
    else
    {
        <input type="hidden" name="editId" value="@Model.AttentionHallPost.Id" />
    }
    @Html.AntiForgeryToken()
    <div class="form-group padding-top">
        <button type="submit" class="btn btn-success">@(Model.AttentionHallPost == null ? "Create" : "Edit") Post</button>
        <a href="/AttentionHall?id=@(Model.AttentionHallPost?.Id ?? 0)" class="btn btn-secondary">Never mind</a>
    </div>
</form>